// src/utils/colorUtils.js
export const COLOR_MAP = {
    slate: {
        bg: "bg-slate-50",
        border: "border-slate-200",
        icon: "text-slate-600",
        val: "text-slate-700",
        ring: "hover:ring-slate-200",
    },
    gray: {
        bg: "bg-gray-50",
        border: "border-gray-200",
        icon: "text-gray-600",
        val: "text-gray-700",
        ring: "hover:ring-gray-200",
    },
    zinc: {
        bg: "bg-zinc-50",
        border: "border-zinc-200",
        icon: "text-zinc-600",
        val: "text-zinc-700",
        ring: "hover:ring-zinc-200",
    },

    red: {
        bg: "bg-red-50",
        border: "border-red-100",
        icon: "text-red-600",
        val: "text-red-700",
        ring: "hover:ring-red-200",
    },
    orange: {
        bg: "bg-blue-50",
        border: "border-blue-100",
        icon: "text-blue-600",
        val: "text-blue-700",
        ring: "hover:ring-blue-200",
    },
    amber: {
        bg: "bg-amber-50",
        border: "border-amber-100",
        icon: "text-amber-600",
        val: "text-amber-700",
        ring: "hover:ring-amber-200",
    },
    yellow: {
        bg: "bg-yellow-50",
        border: "border-yellow-100",
        icon: "text-yellow-600",
        val: "text-yellow-700",
        ring: "hover:ring-yellow-200",
    },
    lime: {
        bg: "bg-lime-50",
        border: "border-lime-100",
        icon: "text-lime-600",
        val: "text-lime-700",
        ring: "hover:ring-lime-200",
    },

    green: {
        bg: "bg-green-50",
        border: "border-green-100",
        icon: "text-green-600",
        val: "text-green-700",
        ring: "hover:ring-green-200",
    },
    emerald: {
        bg: "bg-emerald-50",
        border: "border-emerald-100",
        icon: "text-emerald-600",
        val: "text-emerald-700",
        ring: "hover:ring-emerald-200",
    },
    teal: {
        bg: "bg-teal-50",
        border: "border-teal-100",
        icon: "text-teal-600",
        val: "text-teal-700",
        ring: "hover:ring-teal-200",
    },
    cyan: {
        bg: "bg-cyan-50",
        border: "border-cyan-100",
        icon: "text-cyan-600",
        val: "text-cyan-700",
        ring: "hover:ring-cyan-200",
    },

    sky: {
        bg: "bg-sky-50",
        border: "border-sky-100",
        icon: "text-sky-600",
        val: "text-sky-700",
        ring: "hover:ring-sky-200",
    },
    blue: {
        bg: "bg-blue-50",
        border: "border-blue-100",
        icon: "text-blue-600",
        val: "text-blue-700",
        ring: "hover:ring-blue-200",
    },
    indigo: {
        bg: "bg-blue-50",
        border: "border-blue-100",
        icon: "text-blue-600",
        val: "text-blue-700",
        ring: "hover:ring-blue-200",
    },
    violet: {
        bg: "bg-amber-50",
        border: "border-amber-100",
        icon: "text-amber-600",
        val: "text-amber-700",
        ring: "hover:ring-amber-200",
    },
    purple: {
        bg: "bg-blue-50",
        border: "border-blue-100",
        icon: "text-blue-600",
        val: "text-blue-700",
        ring: "hover:ring-blue-200",
    },
    fuchsia: {
        bg: "bg-fuchsia-50",
        border: "border-fuchsia-100",
        icon: "text-fuchsia-600",
        val: "text-fuchsia-700",
        ring: "hover:ring-fuchsia-200",
    },

    pink: {
        bg: "bg-pink-50",
        border: "border-pink-100",
        icon: "text-pink-600",
        val: "text-pink-700",
        ring: "hover:ring-pink-200",
    },
    rose: {
        bg: "bg-rose-50",
        border: "border-rose-100",
        icon: "text-rose-600",
        val: "text-rose-700",
        ring: "hover:ring-rose-200",
    },

    _default: {
        bg: "bg-slate-50",
        border: "border-slate-200",
        icon: "text-slate-600",
        val: "text-slate-700",
        ring: "hover:ring-slate-200",
    },
};